server:
  port: 8080
  host: localhost

spring:
  cloud:
    config:
      server:
        git:
          uri:https://github.com/Agile-Suite/ConfigServer.git
          clone-on-start: true
          default-label: main

  application:
    name: config-server

message: Hello World! This is the Test application
# This is a simple YAML configuration file.